---
- hosts: webservers
  become: true
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become_method: sudo
    - name: Upgrade packages
      apt:
        upgrade: safe
        autoclean: yes
      become_method: sudo
